### ISSUE TITLE
Enable to specify header tags easier

### ISSUE THREAD

**Issue by kamoii** [pkamenarsky/replica#4]
Hi, thanks for the cool project!

Currently, its hard to specify header tags. You can using `websoketApp` and prepare the index.html file yourself, but I feel `app` function should be able to specify heder tags since its quite normal to use global css style/extenal css/meta tags.

**Comment by pkamenarsky** [comment]
Definitely! I'm also thinking about making embedding things easier - like css or fonts in base64 encoding - in order to eliminate unnecessary network roundtrips. This, combined with server side html rendering would further minimise the time to first-render.
